### ISSUE TITLE
Compatibility with Stardew Fishing for neo 1.21.1

### ISSUE THREAD

**Issue by BrownBear85** [Lightning-64/Tide#99]
**Description**
Neither the Tide minigame nor the Stardew Fishing minigame activate when catching a fish with both mods installed on NeoForge 1.21.1. 

**Additional context**
I just updated Stardew Fishing to neo 1.21.1 and I believe your compatibility code for Stardew Fishing is (understandably) disabled. 

Also, I changed a few parts of the Stardew Fishing codebase and left some deprecated versions with the old parameters for backward compatibility with Tide. If you have the time and motivation to update your usages, here are the changes:
- `data.json` has been renamed to `fish_behaviors.json`. This is the only thing that will print an error in the console, although it will not cause any problems (both locations are still checked for now).
- Stored rewards on `FishingHook`s have been moved to an entity attachment and `FishingHookLogic#getStoredRewards` is now deprecated. Use `entity.getData(SFAttachmentTypes.HOOK).getRewards()` instead. 
- The `ItemStack fishingRod` parameter of `FishingHookLogic#modifyRewards` (both overloads) had been replaced with an `int qualityBoost` parameter. Just pass in 0.

**Comment by Lightning-64** [comment]
Got it, thanks for letting me know. I'll work on fixing all of these, and I should be able to have an update to Tide put out sometime soon.

**Comment by Lightning-64** [comment]
Fixed in the most recent hotfix to 1.6.3

**Comment by VaporeonScripts** [comment]
looks like it isnt fixed, i tried fishing with a normal rod but the minigame didnt start

**Comment by Lightning-64** [comment]
> looks like it isnt fixed, i tried fishing with a normal rod but the minigame didnt start

I just tested, it works for me. Make sure you're using this file

<img width="807" height="106" alt="Image" src="https://github.com/user-attachments/assets/a78455ad-6458-4f44-8e15-733546eafd50" />

**Comment by VaporeonScripts** [comment]
Oh nvm I had tide minigame disabled ,it seems to work
